name: Docker Image CI


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: deneme3/deneme2
      run: mvn clean package

    - name: Build Docker image
      working-directory: deneme3/deneme2
      run: docker build -t deneme2:latest -f path/to/Dockerfile path/to/context
